name: CI

on:
  pull_request:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 */1 * * *"

jobs:
  generate:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: './generate/go.mod'

      - name: Checkout
        uses: actions/checkout@v4

      - name: "Generate README.md"
        run: go run main.go ../README.md
        working-directory: ./generate
      
      - name: Setup Git
        run: |-
          git config --global user.name "Frank Chiarulli Jr."
          git config --global user.email "frank@frankchiarulli.com"

      - name: Commit and push
        run: |-
          git --no-pager diff
          git add README.md || true
          git commit -m "Automatic update via GitHub Action" || true
          git push
