name: CI

on:
  pull_request:
  push:
  schedule:
    - cron: "0 */1 * * *"

env:
  GO_VERSION: 1.19

jobs:
  generate:
    if: github.ref == 'refs/heads/main'
    needs:
      - lint
    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: "Generate README.md"
        run: go run main.go ../README.md
        working-directory: ./generate
      
      - name: Setup Git
        run: |-
          git config --global user.name "Frank Chiarulli Jr."
          git config --global user.email "frank@frankchiarulli.com"

      - name: Commit and push
        run: |-
          git --no-pager diff
          git add README.md || true
          git commit -m "Automatic update via GitHub Action" || true
          git push

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: "Check: golangci-lint"
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: ./generate
          version: v1.50.1
